# Pre Provision Playbook to get base config on a Palo Alto Firewall 

# 1. Set hostname 

---

- name: Palo Alto Playbook
  hosts: palo
  connection: local

  collections:
    - paloaltonetworks.panos

  tasks: 
    - name: Set DNS and Panorama
      panos_mgtconfig: 
        provider: '{{ palo_provider }}'
        dns_server_primary: '{{ dns_primary_ip }}'
        dns_server_secondary: '{{ dns_secondary_ip }}'
        panorama_primary: '{{ panorama_primary_ip }}'
        panorama_secondary: '{{ panorama_secondary_ip }}'
        commit: false
    
    - name: Set backup user account 
      panos_administrator:
        provider: '{{ palo_provider }}'
        admin_username: '{{ adminusername }}'
        admin_password: '{{ adminpassword }}'
        superuser: true
        commit: false 

    - name: Create Server Object
      panos_address_object:
        provider: '{{ palo_provider }}'
        name: 'server1'
        value: '172.16.1.10'
        description: 'vmware'
        state: present

    - name: Create Users Object
      panos_address_object:
        provider: '{{ palo_provider }}'
        name: 'users-subnet'
        value: '10.10.10.0/24'
        description: 'users subnet'
        state: present

    - name: Set Ethernet1/1 as static in zone Outside
      panos_interface: 
        provider: '{{ palo_provider }}'
        if_name: "ethernet1/1"
        mode: "layer3"
        ip: "{{ ip.ethernet1 }}"
        enable_dhcp: false
        zone_name: "Outside"
        
    # - name: Set ports for HA mode 
    #   panos_interface: 
    #     provider: '{{palo_provider}}'
    #     if_name: "{{ item }}"
    #     mode: "ha"
    #     enable_dhcp: false
    #   with_items: 
    #     - ethernet1/3
    #     - ethernet1/4


    - name: Commit 
      panos_commit_firewall:
        provider: '{{ palo_provider }}'