---
## Playbook to configure some stuff 

- hosts: CSR_Routers
  gather_facts: false

  tasks:
  - name: Push config file 
    ios_config:
      src: "~/network-programmability/CONFIGS/test.txt"

  - name: remove username steve
    ios_user: 
      name: steve
      state: absent

  - name: Test reachability to default Router 192.168.1.1
    ios_ping:
      dest: 192.168.1.2

